spring:
  datasource:
    url: jdbc:h2:mem:labjc;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate     # ‚Üê validamos contra Flyway (no auto-crear)
    show-sql: true
  thymeleaf:
    cache: false

spring.h2.console.enabled: true
spring.h2.console.path: /h2

flyway:
  enabled: true
  baseline-on-migrate: true
  locations: classpath:db/migration
